---
version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - tv:/tv #optional
      - downloads:/data #optional
    ports:
      - 8989:8989
    restart: unless-stopped

volumes:
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.12.0.6,nolock,soft,rw"
      device: ":/volume1/ws/downloads"
  tv:
    driver_opts:
      type: "nfs"
      o: "addr=10.12.0.6,nolock,soft,rw"
      device: ":/volume1/ws/media/tv"
