---
- name: Homer Service
  hosts: homer
  vars:
    project_folder: "{{ ansible_env.HOME }}/services/homer"

  tasks:
    - name: Ensure project folder exists
      file:
        path: "{{ project_folder }}"
        state: directory
      tags:
        - run
    - name: Ensure compose file is up to date
      copy:
        src: ./homer/docker-compose.yml
        dest: "{{ project_folder }}/docker-compose.yml"
      tags:
        - run
    - name: Ensure assets are up to date
      copy:
        src: ./homer/assets
        dest: "{{ project_folder }}"
      register: assets_folder
      tags:
        - run
    - name: Start
      community.docker.docker_compose:
        project_src: "{{ project_folder }}"
        state: present
      tags:
        - run
    - name: Restart
      community.docker.docker_compose:
        project_src: "{{ project_folder }}"
        services: homer
        restarted: true
      tags:
        - restart
