- name: Ensure PIP is installed
  become: true
  apt:
    name: python3-pip
    state: present
  tags:
    - deps
- name: Ensure Docker SDK is installed
  pip:
    name:
    - docker
    - docker-compose
  tags:
    - deps

