---
version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - movies:/movies #optional
      - downloads:/data #optional
    ports:
      - 7878:7878
    restart: unless-stopped

volumes:
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.12.0.6,nolock,soft,rw"
      device: ":/volume1/ws/downloads"
  movies:
    driver_opts:
      type: "nfs"
      o: "addr=10.12.0.6,nolock,soft,rw"
      device: ":/volume1/ws/media/movies"
