---
version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true #optional
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
