---
version: "3"
services:
  freshrss:
    image: linuxserver/freshrss:1.20.2
    env_file:
      - .env
    volumes:
      - ./config:/config
    ports:
      - 8087:80
    restart: always
    depends_on:
      - db

  db:
    image: linuxserver/mariadb:10.6.10
    env_file:
      - .env
    volumes:
      - ./db:/config
    restart: always
